[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "2FmfXbj5gPvLD3vjmKKHMsqo14K3VvzxWcJ1zD5pZ8G9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
